name: Build DLL with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended" -y

    - name: Configure CMake
      run: cmake -G "Visual Studio 17 2022" -B build

    - name: Build DLL and Tests
      run: cmake --build build --config Release

    - name: Verify Build Output
      run: |
        if (!(Test-Path -PathType Leaf "build/Release/libroverfsm.dll")) { exit 1 }

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release --output-on-failure

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: libroverfsm-dll
        path: build/Release/libroverfsm.dll
        retention-days: 7  # Optional: Keeps artifact for 7 days
