name: Build DLL with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -G "Visual Studio 17 2022" -B build

    - name: Build DLL and Tests
      run: cmake --build build --config Release

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release --output-on-failure

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: libroverfsm-dll
        path: ${{github.workspace}}/build/Release/libroverfsm.dll
